import mongoose from "mongoose";

// Define the schema for each clothing item
const ClothingItemSchema = new mongoose.Schema({
  name: { type: String, required: true }, // Name of the clothing item (provided by user)
  primaryColor: { type: String, default: null }, // Main color (generated by AI model)
  secondaryColor: { type: String, default: null }, // Optional secondary color (generated by AI model)
  type: { type: String, default: null }, // Type of clothing (e.g., T-shirt, Jacket - generated by AI model)
  texture: { type: String, default: null }, // Texture of the clothing (generated by AI model)
  fabric: { type: String, default: null }, // Fabric type of the clothing (generated by AI model)
  shape: { type: String, default: null }, // Shape of the clothing item (generated by AI model)
  pattern: { type: String, default: null }, // Pattern of the clothing item (e.g., stripes, solid - generated by AI model)
  style: { type: String, default: null }, // Style of the clothing item (e.g., casual, formal - generated by AI model)
  imageUrl: { type: String, required: true }, // URL of the uploaded image (provided by user)
});

const ClothingItem = mongoose.model("ClothingItem", ClothingItemSchema);
export default ClothingItemSchema;
